name = "MyStatPackage"
uuid = "46a2a3bc-0612-419c-8229-658f52acadbd"
authors = ["vladdez <dezem@bk.ru>"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
ProgressMeter = "1.9.0"